// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbba5ORQRsu1xnn9J7CZ0NPhnxSrqojGU',
    appId: '1:1049608875536:android:60f01aa89a8453beeb6495',
    messagingSenderId: '1049608875536',
    projectId: 'petapp-flutter-fd18c',
    storageBucket: 'petapp-flutter-fd18c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDsd8xNai9K-PGarEuRZc17OHP_o0Cc2I',
    appId: '1:1049608875536:ios:8da46e0812d41b99eb6495',
    messagingSenderId: '1049608875536',
    projectId: 'petapp-flutter-fd18c',
    storageBucket: 'petapp-flutter-fd18c.firebasestorage.app',
    androidClientId: '1049608875536-vji3daejslh9lhsad0js8mm4dq284p6h.apps.googleusercontent.com',
    iosClientId: '1049608875536-sdjtd3pfhj3o0k7j5hlbf93cdve8iope.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp',
  );

}